### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by legendskyk** [ItsOnlyBinary/kiwiirc-plugin-avatars#10]
yarn run v1.22.22
$ node build/commands/build.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'webpack'
Require stack:
- /home/kiwiirc/kiwiirc-plugin-avatars/build/commands/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/kiwiirc/kiwiirc-plugin-avatars/build/commands/build.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/kiwiirc/kiwiirc-plugin-avatars/build/commands/build.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

what this error how to reslove it?

**Comment by ItsOnlyBinary** [comment]
you did not run `yarn install`  (also called yarnpkg on debian distros)

**Comment by legendskyk** [comment]
i did that see screen shot:

![image](https://github.com/user-attachments/assets/abeaa8ba-b927-444d-8e3b-6b393f1ca882)

**Comment by ItsOnlyBinary** [comment]
your node is much too old, you will need 16 or newer

or you can download prebuilt here: https://github.com/ItsOnlyBinary/kiwiirc-plugin-avatars/releases

you might need 1.0.4 unless you are running a recent master version of kiwiirc

**Comment by legendskyk** [comment]
let me try it 1.0.4 then let you know it

**Comment by legendskyk** [comment]
same error

**Comment by legendskyk** [comment]
tell me how to update newer node?

**Comment by ItsOnlyBinary** [comment]
the releases dont need building, just download the [kiwiirc-plugin-avatars-v1.0.4.zip](https://github.com/ItsOnlyBinary/kiwiirc-plugin-avatars/releases/download/v1.0.4/kiwiirc-plugin-avatars-v1.0.4.zip) and extact, copy contents to your plugins dir

**Comment by legendskyk** [comment]
you mean it will work without building?

**Comment by ItsOnlyBinary** [comment]
yes those zip's have already been built

**Comment by ItsOnlyBinary** [comment]
https://deb.nodesource.com/   <--- i would suggest using 18.x at the moment, just replace the 20.x for 18.x in the commands
